
on script load:
    broadcast "ExprCurrentFile"
    if file ./test/ExprCurrentFile.txt exists:
        broadcast "false: file already exists (not cleaned up)"
    create file ./test/ExprCurrentFile.txt:
        set the text content of the file to "test"
        add " blob" to the file
    set {_text} to ""
    read file ./test/ExprCurrentFile.txt:
        set {_text} to the text content of the file
    if {_text} is "test blob":
        broadcast "true"
    else:
        broadcast "false: file not edited"
    delete file ./test/ExprCurrentFile.txt
    if file ./test/ExprCurrentFile.txt exists:
        broadcast "false: file not deleted"
