
on script load:
    broadcast "SecOpenRequest"
    set {SecOpenRequest} to 0
    open a website for /SecOpenRequest/ with port 6063:
        set {SecOpenRequest} to 1
        set the status code to 200
        set the text content of the response to "ok"
    set {_text} to ""
    open a web request to http://localhost:6063/SecOpenRequest/:
        set the method of request to "GET"
        await the response:
            set {_text} to the text content of response
    if {_text} is "ok":
        broadcast "true"
    else:
        broadcast "false: response was '%{_text}%'"
    if {SecOpenRequest} is 1:
        broadcast "true"
    else:
        broadcast "false: receiving variable was %{SecOpenRequest}%"
    close the website at /SecOpenRequest/ with port 6063
    delete {SecOpenRequest}
