
on script load:
    broadcast "SecOpenRequest"
    set {SecOpenRequest} to 0
    open a website for /SecOpenRequest/ with port 6063:
        set {SecOpenRequest} to 1
        set the status code to 200
        add "ok" to the response
    set {_text} to ""
    broadcast "X" # todo
    open a web request to https://localhost:6063/SecOpenRequest/:
        broadcast "A" # todo
        set the method of request to "GET"
        broadcast "B" # todo
        await the response:
            broadcast "C" # todo
            set {_text} to the text content of response
            broadcast "D" # todo
        broadcast "E" # todo
    broadcast "F" # todo
    if {_text} is "ok":
        broadcast "true"
    else:
        broadcast "false: response was '%{_text}%'"
    if {SecOpenRequest} is 1:
        broadcast "true"
    else:
        broadcast "false: receiving variable was %{SecOpenRequest}%"
    close the website at /SecOpenRequest/ with port 6063
    delete {SecOpenRequest}
